[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd ../..",
  "pnpm install --no-frozen-lockfile",
  "cd apps/web"
]

[phases.build]
cmds = [
  "cd ../..",
  "pnpm --filter @conferencia/web build",
  "cd apps/web"
]

[start]
cmd = "pnpm preview --host 0.0.0.0 --port $PORT"

