[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/web build"

[deploy]
startCommand = "cd apps/web && npx serve dist -p $PORT -s"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# FORCE DEPLOY - Frontend deve ser servido no domínio principal