[build]
builder = "nixpacks"
buildCommand = "pnpm install && cd apps/web && pnpm build && cd ../api && pnpm build && cd ../.."

[deploy]
startCommand = "cd apps/api && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Full Stack Configuration - Railway
# Frontend + API serving from same domain
# Frontend: turismocinematografico.com.br
# API: turismocinematografico.com.br/api/*