[build]
builder = "nixpacks"
buildCommand = "cd apps/api && npm run build"

[deploy]
startCommand = "cd apps/api && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# FORCE API DEPLOY - Build and serve the API from apps/api directory