[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/api build"

[deploy]
startCommand = "cd apps/api && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
