[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/web build"

[deploy]
startCommand = "cd apps/web && npx serve dist -p $PORT -s"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# URGENTE: FRONTEND DEVE SER SERVIDO NO DOMÍNIO PRINCIPAL
# Site: turismocinematografico.com.br
# Status: ERRO 404 - Precisa servir HTML, não JSON
# Data: 2024-01-XX
# FORÇA ATUALIZAÇÃO: Frontend deve funcionar AGORA!