[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/web build && npm install -g serve"

[deploy]
startCommand = "serve -s apps/web/dist -l $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
