[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/web build"

[deploy]
startCommand = "npx serve apps/web/dist -l $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
