[phases.setup]
nixPkgs = ["chromium"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[env]
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
DISPLAY = ":99"
