[phases.setup]
nixPkgs = ["chromium"]

[phases.install]
cmds = [
  "cd ../.. && npm ci || pnpm install",
  "cd apps/api && npm ci"
]

[phases.build]
cmds = [
  "cd ../web && npm ci && npm run build",
  "cd ../api && npm run build",
  "mkdir -p ../api/dist/web/dist || true",
  "cp -r ../web/dist/* ../api/dist/web/dist/ 2>/dev/null || true"
]

[start]
cmd = "npm start"

[env]
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
DISPLAY = ":99"
