[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm --filter @conferencia/web build && pnpm --filter @conferencia/api build"


[deploy]
startCommand = "cd apps/api && node dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_SKIP_DOWNLOAD = "true"
EMAIL_USER = "litfilmtourismconferenceucs@gmail.com"
EMAIL_PASS = "ownzmecmczapbxfb"
CONFERENCE_EMAIL = "litfilmtourismconferenceucs@gmail.com"
