[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*-chromium-*/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
DISPLAY = ":99"
EMAIL_USER = "litfilmtourismconferenceucs@gmail.com"
EMAIL_PASS = "ownzmecmczapbxfb"
CONFERENCE_EMAIL = "litfilmtourismconferenceucs@gmail.com"
